### ISSUE TITLE
about visualize map

### ISSUE THREAD

**Issue by syxvision** [siyueyu/DCFM#6]
Thank for your nice work. I would like to know how to visualize the response map, like figure 1.Thank you very much.

**Comment by siyueyu** [comment]
@syxvision 
![Screenshot from 2022-10-26 10-06-20](https://user-images.githubusercontent.com/41095128/197917605-5a22c253-0d75-4536-835d-e98d0733f9f9.png)
please check the attached code for the visualization.

**Comment by syxvision** [comment]
Thank you, I will check.
