### ISSUE TITLE
更换backbone

### ISSUE THREAD

**Issue by IceHowe** [siyueyu/DCFM#7]
请问更换backbone后为什么梯度值为None？requires_grad是True，更换后没办法训练了，精度一直在0.44

**Comment by siyueyu** [comment]
@IceHowe 你换成什么了？

**Comment by IceHowe** [comment]
> @IceHowe 你换成什么了？

我一开始换了个Transformer的，发现精度一直是0.4437，后来随便写了个，就是把vgg16里的每个stage只留了一个卷积，然后也一直是0.4437，最后我又换回原本的vgg16，我发现只要train里面这句代码注释掉，精度也一直是0.4437不会变
`model.dcfmnet.backbone._initialize_weights(torch.load('./models/vgg16-397923af.pth'))`
![image](https://user-images.githubusercontent.com/35068131/200557767-833c7b54-7a2e-4360-9272-c1ef3d72dad8.png)
![image](https://user-images.githubusercontent.com/35068131/200557793-6ad2f851-d79f-4065-b4a7-c7368664229e.png)
在第一种情况，也就是我换了backbone时，网络的梯度为None，只有backbone后面的网络梯度不为None，而原本的VGG，去掉加载与训练权重后梯度是有的，可是结果不变，加上就恢复正常了

**Comment by cenchaojun** [comment]
> > @IceHowe 你换成什么了？
> 
> 我一开始换了个Transformer的，发现精度一直是0.4437，后来随便写了个，就是把vgg16里的每个stage只留了一个卷积，然后也一直是0.4437，最后我又换回原本的vgg16，我发现只要train里面这句代码注释掉，精度也一直是0.4437不会变 `model.dcfmnet.backbone._initialize_weights(torch.load('./models/vgg16-397923af.pth'))` ![image](https://user-images.githubusercontent.com/35068131/200557767-833c7b54-7a2e-4360-9272-c1ef3d72dad8.png) ![image](https://user-images.githubusercontent.com/35068131/200557793-6ad2f851-d79f-4065-b4a7-c7368664229e.png) 在第一种情况，也就是我换了backbone时，网络的梯度为None，只有backbone后面的网络梯度不为None，而原本的VGG，去掉加载与训练权重后梯度是有的，可是结果不变，加上就恢复正常了

我也是换了一个resnet，但是训练效果很差，可以加微信聊聊嘛❤️

**Comment by IceHowe** [comment]
> 

嗯，微信：IceHowe

**Comment by IceHowe** [comment]
> > > @IceHowe 你换成什么了？
> > 
> > 
> > 我一开始换了个Transformer的，发现精度一直是0.4437，后来随便写了个，就是把vgg16里的每个stage只留了一个卷积，然后也一直是0.4437，最后我又换回原本的vgg16，我发现只要train里面这句代码注释掉，精度也一直是0.4437不会变 `model.dcfmnet.backbone._initialize_weights(torch.load('./models/vgg16-397923af.pth'))` ![image](https://user-images.githubusercontent.com/35068131/200557767-833c7b54-7a2e-4360-9272-c1ef3d72dad8.png) ![image](https://user-images.githubusercontent.com/35068131/200557793-6ad2f851-d79f-4065-b4a7-c7368664229e.png) 在第一种情况，也就是我换了backbone时，网络的梯度为None，只有backbone后面的网络梯度不为None，而原本的VGG，去掉加载与训练权重后梯度是有的，可是结果不变，加上就恢复正常了
> 
> 我也是换了一个resnet，但是训练效果很差，可以加微信聊聊嘛❤️

嗯，微信：IceHowe

**Comment by IceHowe** [comment]
> 

抱歉，换了backbone不是none，none是因为我打印错模块了，我换了个backbone后，把里面所有的参数初始化去掉了，只在最后加载预训练权重，能训练了，但是问题是训练到20个epoch后精度到了0.6，在之后就全是0.4437了

**Comment by siyueyu** [comment]
@IceHowe 我没试过换backbone，可能无法帮你了。transformer我看人家用的也得先用cnn提取特征的样子。

**Comment by IceHowe** [comment]
> @IceHowe 我没试过换backbone，可能无法帮你了。transformer我看人家用的也得先用cnn提取特征的样子。

好的，感谢，有些小问题，不过换成了
